# Generated by Django 5.2.1 on 2025-05-10 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_remove_reminder_created_at_remove_reminder_remind_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='remind_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='message',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.TimeField(),
        ),
    ]
