# Generated by Django 5.2.1 on 2025-05-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_reminder_remind_at_alter_reminder_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remind_at',
            field=models.DateTimeField(),
        ),
    ]
