# Generated by Django 5.2.1 on 2025-05-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0004_alter_reminder_remind_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(max_length=50),
        ),
    ]
